### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by karan** [schwannden/ndn-on-galileo#1]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

> A novel effort by [**Add a License Please**](https://github.com/karan/add-a-license-please)

**Comment by schwannden** [comment]
There is no code in the book. This is a tutorial, everyone can read it and try to reproduce.
Everyone can copy paste commands as they wish.
